android-pixel-4:
  type: instrumentation
  # Specify the path to the debug and test apks generated early
  app: app/build/outputs/apk/qa/debug/app-qa-debug.apk
  test: app/build/outputs/apk/androidTest/qa/debug/app-qa-debug-androidTest.apk
  device:
    - model: flame
      version: 29
      locale: 'en'
      orientation: portrait
